---
title: "proximity analysis"
author: "Veronica Lee Xuan Hui"
date: "10/25/2020"
output: 
  html_document: 
  toc: true
  toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Packages
```{r}
packages = c('rgdal', 'sf', 'tmap', 'tidyverse', 'sp', 'rgeos','maptools', 'raster', 'spatstat', 'spdep', 'OpenStreetMap', 'tmaptools', 'spatialPosition')
for (p in packages){
  if (!require(p, character.only = T)){
    install.packages(p)
  }
  library(p, character.only = T)
}
```


Combine the centroid and polygons
```{r}
# mpsz_point <- point.in.poly(centroids, mpsz_sf, sp=FALSE, duplicate=FALSE)
```

# Generate Distance Matrices using Euclidean Distance
## Eldercare
rows are facilities, columns are centroids
```{r}
eldercare_dismat <- CreateDistMatrix(knownpts=centroids_demand, 
                                unknownpts=eldercare_sf, 
                                longlat=FALSE)
chas_dismat <- CreateDistMatrix(knownpts=centroids_demand , 
                                unknownpts=chas_sf, 
                                longlat=FALSE)
infocomm_dismat <- CreateDistMatrix(knownpts=centroids_demand, 
                                unknownpts=infocomm_sf, 
                                longlat=FALSE)
```

convert distance matrices from metres to kilometres
```{r}
eldercare_dismat <- as.matrix(eldercare_dismat/1000)
chas_dismat <- as.matrix(chas_dismat/1000)
infocomm_dismat <- as.matrix(infocomm_dismat/1000)
```





# Geographical Accessibility Analysis
## Eldercare
To compute the accessibility of Eldercare services
```{r}
eldercare_acc <- data.frame(ac(centroids_demand$elderly_count,
                               eldercare_sf$capacity, 
                               eldercare_dismat,
                               d0 = 30, 
                               power = 2, 
                               family = 'SAM'))
colnames(eldercare_acc) <- 'accSAM'
eldercare_acc <- tibble::as_tibble(eldercare_acc)

```

```{r}
eldercare_SAM <- bind_cols(mpsz_sf, eldercare_acc)
```

```{r}
sum(is.na(eldercare_SAM))
```

```{r}
tmap_mode('view')
tm_shape(eldercare_SAM) + 
  tm_borders(alpha = 0.5) + 
  tm_fill(col='accSAM', 
          style='pretty')
```
